@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.harleyoconnor.gamepieces.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;